### ISSUE TITLE
Only works with setapp version

### ISSUE THREAD

**Issue by el** [Rahlir/NumiLaunchbar#1]
Required version has setapp bundle identifier. I had to change it to `com.dmitrynikolaev.numi` to make it work. 

Thanks for the extension BTW

**Comment by Rahlir** [comment]
Ups. Thanks for bringing my attention to this. I have updated the Info.plist to default to non-setapp version. If you are installing the extension for setapp Numi, use the install script with -S option:
```bash
./install.sh -S
```
See bbc7f76769954a5734edcce734b375686fca6a93
