### ISSUE TITLE
No live results?

### ISSUE THREAD

**Issue by sinewave** [Rahlir/NumiLaunchbar#2]
Hi, just installed this action however I don't see any live feedback/results when entering text or hitting return. Also seems to sometimes lockup LB.

Is there something else I need to install?

![numi](https://user-images.githubusercontent.com/84384/49487146-0c966b00-f7f6-11e8-9381-c6f5474b4b66.png)

**Comment by Rahlir** [comment]
This is pretty old now, but it sort of sounds like you don't have the actual app [Numi](https://numi.app/) installed on your computer. Or am I wrong?

**Comment by Nigelw** [comment]
I'm having the same issue. I have Numi installed (& running), and when i try to use this action it locks up LaunchBar.

When I check Activity Monitor, I find `at.obdev.LaunchBar.JavaScriptRunnerService` is using a bunch of CPU. If I force quit that process it unfreezes LaunchBar until I try to use this action again and the same thing happens.

**Comment by Nigelw** [comment]
Maybe this is a Ventura thing? I'm running macOS 13.0.1.

**Comment by Nigelw** [comment]
I just realized the issue. I hadn't checked "Enable Alfred integration" in Numi's settings. Oops 😬 

Your LaunchBar action is now working as expected. Thanks so much for this! I ❤️ LaunchBar and really appreciate you making this available.

**Comment by Rahlir** [comment]
Makes sense. The two requirements for this are: have Numi installed and have enabled the option `Enable Alfred integration`. Thanks for letting me know that it works for you now :+1:
